### ISSUE TITLE
Games file path

### ISSUE THREAD

**Issue by SithKillerAlpha** [SvenGDK/XboxMediaUSB#1]
It may be worth changing the games folder paths to match the naming style used by RetroArch/assets or https://github.com/libretro/libretro-database/tree/master/cht so icons and custom backgrounds work instantly.

**Comment by SvenGDK** [comment]
I changed the folder names and added some missing ones, now it shoud work.

**Comment by Jaylinx** [comment]
Another thing, I think "configs" folder should be named "config" as RetroArch does it in fresh install.

**Comment by SvenGDK** [comment]
> Another thing, I think "configs" folder should be named "config" as RetroArch does it in fresh install.

Thanks, I missed this while reading over the folder names. It's now fixed.
