### ISSUE TITLE
Manual scan does not work on some folders

### ISSUE THREAD

**Issue by stuffu** [SvenGDK/XboxMediaUSB#10]
Not sure where the fault is, but a majority of the folder ends up with "no valid content" on a manual scan. The permissions looks the same and verified that there are indeed files in all folders that are added.

I realise this doesn't help much in finding out what might be wrong, but maybe someone came across the same issue before?

**Comment by SvenGDK** [comment]
It could be another permission issue on your drive.

Here's what you can check to get all folders working again :
- Right-click on your drive -> **Properties**
- Compare the **security tab** of the drive with the non working folder one
- Adjust the permissions of the non working folder for every group & user name to the permissions of the root drive
- Remove the "???" groups & users if there are any
- Also check the **Advanced** permissions settings

In case you don't have "ALL APPLICATION PACKAGES" in the "Group or user names" then select the drive again in XboxMedia USB and use "Add permissions to drive".

This could resolve your issue with accessing all folders on the drive.
