### ISSUE TITLE
C:\ & Z:\ drive is selectable in the list of drives

### ISSUE THREAD

**Issue by Gamr13** [SvenGDK/XboxMediaUSB#3]
C:\ is typically reserved as the main drive's letter for the OS, and should probably be hidden by default (if possible) as it's not a removable drive in 99% of cases

Z:\ is usually for network shares and should also be hidden by default (if possible)

<3

**Comment by SvenGDK** [comment]
Hiding the C:\ drive is possible, but you can install Windows on a different drive letter as C:\ and it's also possible to change the system drive letter with the Disk Management tool on Windows.
Z:\ can also be an external drive, just tested it :)
