### ISSUE TITLE
Adding a Spanish Translation

### ISSUE THREAD

**Issue by GABO1423** [SvenGDK/XboxMediaUSB#4]
Hi! I just wanted to thank you for this tool, really made a lot of our lives easier. 

I saw that this now supported multiple languages, but Spanish was not one of them. So, I decided to make one. I saw that the language files are not included in the code itself, so I made this issue just to share it. Hope to see it included in the next release.

Thanks in advance for reading, here's the .ini file:

[Spanish Translation.zip](https://github.com/SvenGDK/XboxMediaUSB/files/9893914/Spanish.Translation.zip)

**Comment by SvenGDK** [comment]
Thanks for your support, Spanish has been added to a new release.
