### ISSUE TITLE
[ISSUE] - XboxMediaUSB v2.0 - x64 (notARM)

### ISSUE THREAD

**Issue by PepeCobain95** [SvenGDK/XboxMediaUSB#6]
the program won't let me format.

1)To be able to format, I had to format it through Windows
2)Open the program and 
3)go to "modify an existing USB drive" -> select drive letter -> "Add to permission to drive"
4)go to "prepare new a USB drive" -> select drive letter-> create default folders

ISSUE

"Set USB drive" and "Set USB icon and text" do not work

Also you cannot format from the tool from "Prepare new a USB drive"

You must necessarily follow the steps I mentioned above otherwise the tool will loop load the drive by disconnecting it and reconnecting after some time

while if you will ask to load the USB icon or USB Icon and text the program will ask for closing

![image](https://user-images.githubusercontent.com/131243507/233008531-e9d80fda-1cc5-4c81-888b-240c69fbf3f3.png)

**Comment by SvenGDK** [comment]
> the program won't let me format.
> 
> 1)To be able to format, I had to format it through Windows 2)Open the program and 3)go to "modify an existing USB drive" -> select drive letter -> "Add to permission to drive" 4)go to "prepare new a USB drive" -> select drive letter-> create default folders
> 
> ISSUE
> 
> "Set USB drive" and "Set USB icon and text" do not work
> 
> Also you cannot format from the tool from "Prepare new a USB drive"
> 
> You must necessarily follow the steps I mentioned above otherwise the tool will loop load the drive by disconnecting it and reconnecting after some time
> 
> while if you will ask to load the USB icon or USB Icon and text the program will ask for closing
> 
> ![image](https://user-images.githubusercontent.com/131243507/233008531-e9d80fda-1cc5-4c81-888b-240c69fbf3f3.png)

Can you please try again with v2.1 and check if the problem still exists ?
If yes, does it work with a different USB drive ?
