### ISSUE TITLE
Win 10 PC Newest .NET "This App Cant Run On Your PC" Error

### ISSUE THREAD

**Issue by MaskedMayhem102** [SvenGDK/XboxMediaUSB#8]
UPDATE: I have Both X64 OS and Architecture But, only 32x works

**Comment by sizarsami** [comment]
What’s the solution??

**Comment by SvenGDK** [comment]
Please try again with the v2.2 release :
https://github.com/SvenGDK/XboxMediaUSB/releases/tag/v2.2

You can open a new issue here on GitHub in case it doesn't work.
