### ISSUE TITLE
Bug that could lead to formatting the wrong drive

### ISSUE THREAD

**Issue by charnet3d** [SvenGDK/XboxMediaUSB#9]
I encountered a bug in the UI, where you can potentially format the drive selected in the right side (in the "Modify existing USB drive" list). Though I didn't do a test to see if this is visual only or it does format the wrong drive.

Steps to reproduce:
1- Connect 2 USB drives (say L:\ and N:\).
2- Open XboxMediaUSB.
3- On the left side select N:\ for formatting, check "Set USB drive icon".
4- On the right side select L:\ and click "Set USB drive icon". In my case it said "Autorun already exists" and "Icon already exists", maybe this could be relevant to the bug.
5- Click Format USB to format N:\ previously selected on the left side, It now asks you if you want to format L:\ from the right side, which is wrong and dangerous. It probably remembers the last action from setting the icon earlier.
There should be an independent variable for each combo box so they don't mix up.

![image](https://github.com/SvenGDK/XboxMediaUSB/assets/2863796/17a56593-f7b8-41a9-86ad-fd68e00d87e2)

**Comment by SvenGDK** [comment]
> I encountered a bug in the UI, where you can potentially format the drive selected in the right side (in the "Modify existing USB drive" list). Though I didn't do a test to see if this is visual only or it does format the wrong drive.
> 
> Steps to reproduce: 1- Connect 2 USB drives (say L:\ and N:). 2- Open XboxMediaUSB. 3- On the left side select N:\ for formatting, check "Set USB drive icon". 4- On the right side select L:\ and click "Set USB drive icon". In my case it said "Autorun already exists" and "Icon already exists", maybe this could be relevant to the bug. 5- Click Format USB to format N:\ previously selected on the left side, It now asks you if you want to format L:\ from the right side, which is wrong and dangerous. It probably remembers the last action from setting the icon earlier. There should be an independent variable for each combo box so they don't mix up.
> 
> ![image](https://private-user-images.githubusercontent.com/2863796/287558900-17a56593-f7b8-41a9-86ad-fd68e00d87e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MjYwMjksIm5iZiI6MTcyMTYyNTcyOSwicGF0aCI6Ii8yODYzNzk2LzI4NzU1ODkwMC0xN2E1NjU5My1mN2I4LTQxYTktODZhZC1mZDY4ZTAwZDg3ZTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDUyMjA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGIxOThhOWJmNWYwOGRhMWM1NWUxNjdhOWQyNmY1NTY5NmI2MTE4YjU2YmU3NjJiNWQ1OTM0NmRkZGU4NjhhNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xLdM3i7oh2HTJ1P8yoLYJ8SbYvHzZOJeiu4mxClUfoo)

Thanks for mentioning this issue, it has been fixed in the v2.2 release :
https://github.com/SvenGDK/XboxMediaUSB/releases/tag/v2.2
